version: '3.8'

services:
    
  mysql:
    image: mysql/mysql-server:5.7
    volumes:
      - mobilize_db:/db/
    ports:
      - 3306:3306
    expose:
      # Opens port 3306 on the container
      - '3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=mobilize
      - MYSQL_USER=mobilize
      - MYSQL_PASSWORD=mobilizepass_2

    command: 
      --sql-mode=""
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    restart: on-failure
      
  mobilize:
    build: .
    restart: always

    ports:
#      - "188.225.86.132:8000:8000"

    expose:
     - '465'
     - '5000'
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - SECRET_KEY=mobilizesecret342
      - MAIL_SERVER=smtp.mail.ru
      - MAIL_PORT=465
      - MAIL_USE_SSL=1
      - MAIL_USERNAME=chaikide@mail.ru
      - MAIL_PASSWORD=r20tfKbzMgASvYb8m1bY
      - "DATABASE_URL=mysql+pymysql://mobilize:mobilizepass_2@mysql/mobilize"
      - DB_HOST=mysql
      - DEBUG=False
      
    volumes:
      - mobilize_photos:/home/mobilize/apps/static/assets/img/photos
      - static_volume:/home/mobilize/apps/static
    depends_on:
      - mysql
            
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - mobilize
    volumes:
      - static_volume:/home/mobilize/apps/static

volumes:
  mobilize_photos:
  mobilize_db:

      